spring:

  application:
    name: "transactions"

  datasource:
    url: jdbc:postgresql://localhost:5433/transactionsBatch    #testPerforV2
    username: postgres
    password: imad
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

batch:
  input:

    filePath: "file:C:/Users/msi/Downloads/ArtifactTest (1)/ArtifactTest/src/main/resources/transactions.json"
    targetType: "com.S2M.ArtifactTest.Demo.DTO.Transaction"
    names:
      - "reference"
      - "amount"
      - "currency"
      - "accountNumber"
   # linesToSkip: 1
   # encoding: "UTF-8"


    # --- Delimited File Specific Properties ---
    #type: DELIMITED
    #delimiter: ","
    # quoteCharacter: "\"" # Optional
    type: json
    #column-ranges: "1-6,7-12,13-15,16-19"
