spring:

  application:
    name: "transactions"

  datasource:
    url: jdbc:postgresql://localhost:5433/transactionsBatch    #testPerforV2
    username: postgres
    password: imad
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true




batch:
  input:
    filePath: "file:C:/Users/msi/Downloads/ArtifactTest (1)/ArtifactTest/src/main/resources/transactions.csv"
    target-type: "com.S2M.ArtifactTest.Demo.DTO.Transaction"
    lines-to-skip: 1
    names:
      - "reference"
      - "amount"
      - "currency"
      - "accountNumber"
    type: DELIMITED

job :
  execution:
    job-type:  MULTI_THREADED_STEP
    job-name: "JOQQDDDF34543"
    step-name: "STEP6555"



#batch:
#  input:
#    filePath: "file:C:/Users/msi/Downloads/ArtifactTest (1)/ArtifactTest/src/main/resources/transactions.JSON"
#    target-type: "com.S2M.ArtifactTest.Demo.DTO.Transaction"
#    type: JSON


#batch:
#  input:
#    filePath: "file:C:/Users/msi/Downloads/ArtifactTest (1)/ArtifactTest/src/main/resources/transactionsFixedLength.txt"
#    target-type: "com.S2M.ArtifactTest.Demo.DTO.Transaction"
#    names:
#      - "reference"
#      - "amount"
#      - "currency"
#      - "accountNumber"
#    type: FIXED_LENGTH
#    column-ranges: "1-6,7-12,13-15,16-19"








#batch:
#  input:
#    database:
#      targetType: "com.S2M.ArtifactTest.Demo.DTO.TransactionDTO"
#      tableName: "transactions_dto2"
#      whereClause: "MOD(CAST(SUBSTRING(reference_update, 4) AS INTEGER), 2) = :evenRemainder"
#      parameterValues:
#          evenRemainder: 0
#      sortKeys:
#        reference_update: "ASC"
#      columnMappings:
#        reference: "reference_update"
#      pageSize: 2
#      select-clause:
#      reader-type: jdbc

#batch:
#  input:
#    database:
#      targetType: "com.S2M.ArtifactTest.Demo.DTO.TransactionDTO"
#      reader-type: JDBC
#      table-name: "transactions_dto"
#      select-clause: "reference"
#      whereClause: "MOD(CAST(SUBSTRING(reference, 4) AS INTEGER), 2) = :evenRemainder"
#      parameterValues:
#        evenRemainder: 0
#
#      sort-keys:
#        reference: ASC



#batch:
#  input:
#    database:
#      targetType: "com.S2M.ArtifactTest.Demo.DTO.TransactionDTO"
#      service-bean-name: "transactionDTORepository"
#      service-method-name: "findByAmountGreaterThan"
#      page-size: 2
#      repository-method-arguments:
#        - 290.00  # Argument for 'amount'
#      repository-sorts:
#        - "amount,DESC"
#        - "reference,ASC"
#      reader-type: REPOSITORY




